language: node_js
node_js:
  - "8"
  
cache:
  yarn: true
  directories:
    - "node_modules"
  
script:
  - cd web
  - yarn
  - yarn build
  - cd ../
  - docker build ./ -t fengmu456/enok-blog
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push fengmu456/enok-blog
