language: node_js
node_js:
  - "8"

services:
  - mysql
  - docker
  - redis-server
  
cache:
  yarn: true
  
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  
script:
  - env
  #- cd web
  #- yarn
  #- yarn build
  - cd ../
  - docker build ./ -t registry.cn-hangzhou.aliyuncs.com/manyuanrong-public/enok-blog --network host
  - docker push registry.cn-hangzhou.aliyuncs.com/manyuanrong-public/enok-blog
