language: node_js
node_js:
  - "8"
  
cache:
  yarn: true
  directories:
    - "node_modules"

before_install:
  - mkdir -p ~/.ssh
  - openssl aes-256-cbc -K $encrypted_6c4c412cdcb9_key -iv $encrypted_6c4c412cdcb9_iv -in id_rsa.enc -out ~\/.ssh/id_rsa -d
  
script:
  - cd web
  - yarn
  - yarn build
  - cd ../
  - docker build ./ -t fengmu456/enok-blog
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push fengmu456/enok-blog

after_success:
  - ssh $DEPLOY_HOST "source /etc/profile;/data/travis/enok-blog.sh"
